In [32]:
import pandas as pd
import numpy as np

In [33]:
songs=pd.read_csv("songs.csv")

In [34]:
songs=songs.drop('link',axis=1).reset_index(drop=True)

In [35]:
songs

,artist,song,text
0,ABBA,Ahe's My Kind Of Girl,"Look at her face, it's a wonderful face \nAnd..."
1,ABBA,"Andante, Andante","Take it easy with me, please \nTouch me gentl..."
2,ABBA,As Good As New,I'll never know why I had to go \nWhy I had t...
3,ABBA,Bang,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,Making somebody happy is a question of give an...
...,...,...,...
57645,Ziggy Marley,Good Old Days,Irie days come on play \nLet the angels fly l...
57646,Ziggy Marley,Hand To Mouth,Power to the workers \nMore power \nPower to...
57647,Zwan,Come With Me,all you need \nis something i'll believe \nf...
57648,Zwan,Desire,northern star \nam i frightened \nwhere can ...
57649,Zwan,Heartsong,come in \nmake yourself at home \ni'm a bit ...

Preprocessing

In [36]:

songs['text']=songs['text'].str.lower().str.replace('\r', '').str.replace('\n', '')

In [37]:
songs

,artist,song,text
0,ABBA,Ahe's My Kind Of Girl,"look at her face, it's a wonderful face and i..."
1,ABBA,"Andante, Andante","take it easy with me, please touch me gently ..."
2,ABBA,As Good As New,i'll never know why i had to go why i had to ...
3,ABBA,Bang,making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,making somebody happy is a question of give an...
...,...,...,...
57645,Ziggy Marley,Good Old Days,irie days come on play let the angels fly let...
57646,Ziggy Marley,Hand To Mouth,power to the workers more power power to the...
57647,Zwan,Come With Me,all you need is something i'll believe flash...
57648,Zwan,Desire,northern star am i frightened where can i go...
57649,Zwan,Heartsong,come in make yourself at home i'm a bit late...

In [38]:
# songs['text']=songs['text'].str.replace('\\r', '').str.replace('\\n', '')
songs['song']=songs['song'].str.lower()

In [39]:
songs = songs[songs['artist'].isin(["Travis Scott", "Adele", "Beyoncé", "Ed Sheeran", "Taylor Swift", "Bruno Mars", "Ariana Grande", "The Weeknd", "Lady Gaga", "Rihanna", "Justin Bieber", "Sam Smith", "Billie Eilish", "Post Malone", "Drake", "Katy Perry", "Shawn Mendes", "Sia", "John Legend", "Dua Lipa", "Harry Styles", "Maroon 5", "Kendrick Lamar", "Imagine Dragons", "Coldplay", "P!nk", "Camila Cabello", "Demi Lovato", "Halsey", "Selena Gomez", "Charlie Puth", "Lizzo", "Lorde", "Eminem", "Lana Del Rey", "Alessia Cara", "Doja Cat", "Lewis Capaldi", "Lauv", "Marshmello", "Khalid", "Twenty One Pilots", "Panic! At The Disco", "Mariah Carey", "Cardi B", "Megan Thee Stallion", "Nicki Minaj", "Ellie Goulding", "Calvin Harris", "Zedd", "Miley Cyrus", "Tones and I", "Ava Max", "Zayn", "Troye Sivan", "SZA", "Lil Nas X", "J Balvin", "Bad Bunny", "Maluma", "Shakira", "Jennifer Lopez", "Pitbull", "Jason Derulo", "Daft Punk", "The Chainsmokers", "Zedd", "David Guetta", "Avicii", "Bastille", "Hozier", "James Arthur", "Jess Glynne", "Clean Bandit", "Ellie Goulding", "Rita Ora", "Bebe Rexha", "Jessie J", "Meghan Trainor", "Charlie XCX", "Tove Lo", "Rag'n'Bone Man", "George Ezra", "Anne-Marie", "Jax Jones", "Jonas Blue", "Sigala", "Disclosure", "Sam Feldt", "Kygo", "Martin Garrix", "Alan Walker", "Galantis", "Diplo", "Major Lazer", "DJ Snake", "Skrillex", "Flume", "Rudimental", "Disclosure", "Years & Years", "Jess Glynne", "Ella Henderson", "Becky Hill", "Joel Corry", "MNEK"])]

In [40]:
# get random 5000 songs
# songs=songs.sample(2000).reset_index(drop=True)
songs=songs.reset_index(drop=True)

In [41]:
songs['recommend'] = None

In [42]:
songs

,artist,song,text,recommend
0,Adele,all i ask,[verse 1] i will leave my heart at the door ...,None
1,Adele,can't let go,"[verse 1] when did it go wrong, i will never ...",None
2,Adele,crazy for you,"found myself today singing out your name, you...",None
3,Adele,daydreamer,daydreamer sitting on the sea soaking up the...,None
4,Adele,hello,"[verse 1] hello, it's me i was wondering if ...",None
...,...,...,...,...
2627,Twenty One Pilots,semi-automatic,"night falls, with gravity. the earth turns, f...",None
2628,Twenty One Pilots,taken by sleep,this is a story about a scarlet letter... yeah...,None
2629,Twenty One Pilots,the judge,na na na na oh oh na na na na oh oh na na na...,None
2630,Twenty One Pilots,trapdoor,"he wakes up early today, throws on a mask tha...",None
2631,Twenty One Pilots,trees,i know where you stand silent in the trees ...,None

In [43]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# Download necessary datasets
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [44]:
# Initialize the stemmer
stemmer = PorterStemmer()

# Get the list of stopwords in English
stop_words = set(stopwords.words('english'))

In [45]:
def token(elm):
    tok = nltk.word_tokenize(elm)
    a = [stemmer.stem(x) for x in tok if x.lower() not in stop_words]
    return ' '.join(a)

In [46]:
songs['text'] = songs['text'].apply(lambda x: token(x))

In [47]:
songs

,artist,song,text,recommend
0,Adele,all i ask,[ vers 1 ] leav heart door wo n't say word 've...,None
1,Adele,can't let go,"[ vers 1 ] go wrong , never know love life slo...",None
2,Adele,crazy for you,"found today sing name , said 'm crazi , 'm cra...",None
3,Adele,daydreamer,daydream sit sea soak sun real lover make past...,None
4,Adele,hello,"[ vers 1 ] hello , 's wonder year 'd like meet...",None
...,...,...,...,...
2627,Twenty One Pilots,semi-automatic,"night fall , graviti . earth turn , saniti tak...",None
2628,Twenty One Pilots,taken by sleep,"stori scarlet letter ... yeah . hit lay head ,...",None
2629,Twenty One Pilots,the judge,na na na na oh oh na na na na oh oh na na na n...,None
2630,Twenty One Pilots,trapdoor,"wake earli today , throw mask alter face . one...",None
2631,Twenty One Pilots,trees,know stand silent tree 's silent tree wo n't s...,None

In [48]:
songs['artist']=songs['artist'].str.lower()

In [49]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
tfid=TfidfVectorizer(analyzer='word')

In [51]:
matrix=tfid.fit_transform(songs['text'])

In [52]:
similarity=cosine_similarity(matrix)

In [53]:
similarity[0]

array([1.        , 0.12508816, 0.03287493, ..., 0.0968893 , 0.14340893,
       0.02639585])

Recommender function

In [61]:
def recommender(song_name):
    try:
        i = songs[songs['song'] == song_name].index[0]
    except IndexError:
        # Handle the case where the song doesn't exist
        return ["Sorry song not found in database"]

    distances = sorted(enumerate(similarity[i]), key=lambda x: x[1], reverse=True)
    song_indices = [index for index, _ in distances[1:11]]  # Exclude the input song itself

    recommended_songs = []
    for index in song_indices:
        song = songs.loc[index, 'song']
        artist = songs.loc[index, 'artist']
        recommended_songs.append(song + '   ' + artist + '\n')

    return ''.join(recommended_songs)

In [55]:
for index, row in songs.iterrows():
    song_name = row['song']
    recommendations = recommender(song_name)
    songs.at[index, 'recommend'] = recommendations

In [56]:
songs['recommend'].iloc[84]

"breakout   miley cyrus\nbreakout   katy perry\nhalcyon   ellie goulding\nthis is our song   demi lovato\nbe alright   ariana grande\nso what   p!nk\nyou're gonna love me   lana del rey\ntake it all   adele\nbrand new day   demi lovato\na message   coldplay\n"

In [57]:
songs

,artist,song,text,recommend
0,adele,all i ask,[ vers 1 ] leav heart door wo n't say word 've...,i'm real jennifer lopez\nlike i can sam sm...
1,adele,can't let go,"[ vers 1 ] go wrong , never know love life slo...",loving you jennifer lopez\njason's song (gav...
2,adele,crazy for you,"found today sing name , said 'm crazi , 'm cra...",crazy miley cyrus\ni get crazy nicki minaj...
3,adele,daydreamer,daydream sit sea soak sun real lover make past...,taken for granted sia\nall my life mariah ...
4,adele,hello,"[ vers 1 ] hello , 's wonder year 'd like meet...","hello, hello lady gaga\nhello maroon 5\nso..."
...,...,...,...,...
2627,twenty one pilots,semi-automatic,"night fall , graviti . earth turn , saniti tak...",everything you're not demi lovato\nthe way i...
2628,twenty one pilots,taken by sleep,"stori scarlet letter ... yeah . hit lay head ,...",the last song rihanna\nfriends ed sheeran\...
2629,twenty one pilots,the judge,na na na na oh oh na na na na oh oh na na na n...,what is love jennifer lopez\ni'm into you ...
2630,twenty one pilots,trapdoor,"wake earli today , throw mask alter face . one...",bleeding out imagine dragons\nthis ed shee...
2631,twenty one pilots,trees,know stand silent tree 's silent tree wo n't s...,"hello, hello lady gaga\nhello maroon 5\nhe..."

In [58]:
# import json

# data_to_export = {
#     "songs": songs.to_dict(orient="records")
# }

# with open('songsmodel.json', 'w') as file:
#     json.dump(data_to_export, file)

In [63]:
recommendation = recommender('l')
print(recommendation)

['Sorry song not found in database']

In [60]:
ss=songs[songs['song'].isin(["shawn mendes", "miley cyrus"])]
ss

Empty DataFrame
Columns: [artist, song, text, recommend]
Index: []